/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-bright": "#2c3a4a",
        "outline-variant": "#43474a",
        "on-primary-fixed": "#151d20",
        "primary": "#3CBAB2",
        "on-primary": "#0B1A28",
        "on-surface": "#E8F0F5",
        "secondary": "#b3cada",
        "on-tertiary-fixed-variant": "#00504c",
        "on-background": "#E8F0F5",
        "primary-container": "#1d3d3b",
        "surface-container-highest": "#283645",
        "on-primary-container": "#80f6ed",
        "on-error-container": "#ffdad6",
        "outline": "#8d9194",
        "surface-container-low": "#0e1d2b",
        "tertiary-container": "#80f6ed",
        "inverse-on-surface": "#233241",
        "error-container": "#93000a",
        "surface-container-lowest": "#020f1d",
        "on-secondary-container": "#a2b8c8",
        "surface-container": "#12212f",
        "primary-fixed-dim": "#c0c8cd",
        "on-surface-variant": "#c4c7c9",
        "error": "#ffb4ab",
        "primary-fixed": "#dce4e9",
        "on-tertiary-container": "#00716b",
        "on-primary-fixed-variant": "#40484c",
        "surface": "#142637",
        "secondary-fixed": "#cfe6f7",
        "on-tertiary": "#003734",
        "secondary-container": "#344957",
        "on-tertiary-fixed": "#00201e",
        "tertiary-fixed": "#80f6ed",
        "on-error": "#690005",
        "surface-container-high": "#1d2b3a",
        "on-secondary": "#1d3340",
        "surface-dim": "#051422",
        "inverse-surface": "#d5e4f8",
        "tertiary-fixed-dim": "#61d9d0",
        "secondary-fixed-dim": "#b3cada",
        "inverse-primary": "#576064",
        "tertiary": "#3CBAB2",
        "surface-tint": "#c0c8cd",
        "surface-variant": "#283645",
        "on-secondary-fixed": "#061e2a",
        "on-secondary-fixed-variant": "#344957",
        "background": "#0B1A28"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "8px",
        "lg": "32px",
        "md": "16px",
        "xl": "64px",
        "container-margin": "24px",
        "gutter": "16px"
      },
      fontFamily: {
        "h2": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Roboto Mono", "monospace"],
        "display-mobile": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"]
      },
      fontSize: {
        "h2": ["2rem", {"lineHeight": "1.3", "fontWeight": "400"}],
        "body-lg": ["1.125rem", {"lineHeight": "1.6", "fontWeight": "400"}],
        "display": ["4.5rem", {"lineHeight": "1.1", "letterSpacing": "-0.015em", "fontWeight": "400"}],
        "body-md": ["1rem", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-sm": ["0.75rem", {"lineHeight": "1", "letterSpacing": "0.04em", "fontWeight": "400"}],
        "display-mobile": ["3rem", {"lineHeight": "1.1", "fontWeight": "400"}],
        "h1": ["2.5rem", {"lineHeight": "1.2", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
