name: mobile
description: "FloodAid - Nền tảng Hỗ trợ Điều phối Cứu trợ Lũ lụt"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.7.0
  firebase_messaging: ^15.2.5
  
  # HTTP & API
  http: ^1.6.0
  
  # GPS & Location
  geolocator: ^14.0.2
  
  # Local Storage
  shared_preferences: ^2.3.0
  
  # UI
  google_fonts: ^6.2.1
  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  web_socket_channel: ^3.0.2
  
  # Speech to Text
  speech_to_text: ^7.0.0

  # Local Notifications (System-level, giống Messenger/MBBank)
  flutter_local_notifications: ^19.0.0
  connectivity_plus: ^7.1.1
  shimmer: ^3.0.0
  lucide_icons: ^0.257.0
  flutter_screenutil: ^5.9.3

  # eKYC — Chụp ảnh CCCD
  image_picker: ^1.1.2
  lottie: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/dialect_dict.json
    - assets/lottie/
